IMAGE_SERVER_BASE_URL:
  http://192.168.0.50/
FDFS_CLIENT_URL:
  classpath:fdfs_client.conf
#################redis线程池设置#################
# 连接池中的最大空闲连接，默认值也是8。
# spring.redis.pool.max-idle=500
#连接池中的最小空闲连接，默认值也是0。
# spring.redis.pool.min-idle=50
# 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
# spring.redis.pool.max-active=2000
# 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
# spring.redis.pool.max-wait=1000

#################redis哨兵设置#################
# Redis服务器master的名字
#spring.redis.sentinel.master=master8026
# redis-sentinel的配置地址和端口
#spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378
spring:
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101/rms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Aqq1!50796726
    initialSize: 2
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 3600000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select current_timestamp()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #################redis基础配置#################
    redis:
      database: 5
      host: localhost
      port: 6379
      # 连接超时时间 单位 ms（毫秒）
      timeout: 3000
    application:
      name: youngsun-admin
mybatis:
    type-aliases-package: com.youngsun.admin.*.entity
    mapper-locations: classpath:/com/youngsun/admin/*/mapper/*.xml
mapper:
    mappers:
      - com.youngsun.common.mapper.MyMapper
    not-empty: false
    identity: MYSQL
    order: BEFORE
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:1000/eureka
      #,http://192.168.0.102:1000/eureka,http://192.168.0.106:1000/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000000 #缺省为1000

youngsun-rms-user:
  ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
